更新水晶編年史
SlimeTraditionalTranslation/CrystamaeHistoria pull request #5
Opened 2022-03-29 05:19 UTC by xMikux

正在翻譯新內容中 目前的版本位置 DEV - 61~65

2022-03-29 11:16 UTC, weiii-joe requested changes

2022-03-29 11:16 UTC, weiii-joe commented on src/main/java/io/github/sefiraat/crystamaehistoria/slimefun/items/tools/RecallingCrystaLattice.java
> +                    MessageFormat.format("{0}Type the name of this Waystone into chat.", ChatColor.LIGHT_PURPLE)
在聊天室輸入這個岔出的路石的名稱.

2022-03-30 01:27 UTC, weiii-joe requested changes
此問題是錯誤 nome

2022-03-30 01:27 UTC, weiii-joe commented on README.md
> +A big thanks to the owners of **mct.tantrum.org** who have tested nearly everything I have made and really given me
102~106 行缺失翻譯

2022-03-30 01:28 UTC, weiii-joe approved these changes

2022-03-30 02:08 UTC, xwinhyukx approved these changes
lgtm

2022-03-30 03:52 UTC, merged